version: "3"
services:
  nginx:
   image : nginx:latest
   ports :
       - "8080:8080"
       - "80:80"
       - "443:443"
   volumes:
       - ./ssl:/etc/nginx/ssl
       - ./nginx.conf:/etc/nginx/conf.d/default.conf